[Dubbo-3570] repackage compatible enhancement. (#3622)
* Fixes #3570, NoSuchMethodError are thrown when add custorm Filter using dubbo2.6.5 and JDK1.6 and upgrade to dubbo2.7.0
* Add compatible UT
* fix UT